---
title: "Assignment06"
output: html_document
date: "2024-04-02"
---

```{r}
#Loading required libraries
library(DAAG)
library(party)
library(rpart)
library(rpart.plot)
library(mlbench)
library(pROC)
library(tree)
library(caret)
library(rpart)
library(rpart.plot)
library(caret)
library(pROC)
```
```{r}
```

```{r}
#loading the dataset
churndata = read.csv("/Users/bhanuprasadthota/Downloads/churn.csv", header = T )
str(churndata)
```

```{r}
#Omitting unrequired columns
churndata$V4 = NULL
str(churndata)
```

```{r}
# Converting specific columns to factor variables
churndata$V1 = as.factor(churndata$V1) # State
churndata$V3 = as.factor(churndata$V3) # Area Code
churndata$V5 = as.factor(churndata$V5) # International Plan
churndata$V6 = as.factor(churndata$V6) # Voice Mail Plan
churndata$V21 = as.factor(churndata$V21) # Churn

# Check the structure of the data frame to confirm changes
str(churndata)

```

```{r}
#splitting the data in to train and test data
set.seed(1234)
ind = sample(2, nrow(churndata), replace = TRUE, prob = c(0.8, 0.2))
train = churndata[ind == 1, ]
test = churndata[ind == 2, ]

```
```{r}
#Decision Tree
tree = rpart(V21 ~ ., data = train, method = "class")
rpart.plot(tree)
printcp(tree)
plotcp(tree)
```
```{r}
#viewing the decision tree physically
library(rpart.plot)
rpart.plot(tree, type = 4, extra = 6)


```
```{r}
#Evaluation of tree model using confusion matrix on train data
ptrain = predict(tree, train, type = 'class')
confusionMatrix(ptrain, train$V21)

```
```{r}
#Evaluation of tree model using confusion matrix on test data
ptest = predict(tree, test, type = 'class')
confusionMatrix(ptest, test$V21)
```
```{r}
# ROC Curve
p <- predict(tree, test, type = 'prob')
p <- p[,2]
r <- multiclass.roc(test$V21, p1, percent = TRUE)
roc <- r[['rocs']]
r <- roc[[1]]
plot.roc(r,
         print.auc=TRUE, 
         auc.polygon=TRUE, 
         grid=c(0.1, 0.5),
         grid.col=c("blue", "red"), 
         max.auc.polygon=TRUE,
         auc.polygon.col="lightgreen", 
         print.thres=TRUE, 
         main= 'Churn Data ROC Curve')

```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

